/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    products: Product;
    orders: Order;
    'order-items': OrderItem;
    deliveries: Delivery;
    media: Media;
    'tracking-events': TrackingEvent;
    reviews: Review;
    'customer-notifications': CustomerNotification;
    'support-messages': SupportMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    deliveries: DeliveriesSelect<false> | DeliveriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'tracking-events': TrackingEventsSelect<false> | TrackingEventsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'customer-notifications': CustomerNotificationsSelect<false> | CustomerNotificationsSelect<true>;
    'support-messages': SupportMessagesSelect<false> | SupportMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    settings: Setting;
    'store-content': StoreContent;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'store-content': StoreContentSelect<false> | StoreContentSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super_admin' | 'operador' | 'marketing' | 'cliente' | 'delivery';
  subRole?: string | null;
  nombre: string;
  apellido: string;
  nombreCompleto?: string | null;
  telefono?: string | null;
  /**
   * El cliente puede editarla desde su cuenta. Se usa para precargar el checkout.
   */
  delivery_address?: {
    street?: string | null;
    city?: string | null;
    province?: string | null;
    reference?: string | null;
  };
  /**
   * Persona alternativa de contacto para entregas.
   */
  contact_secondary?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Imagen de perfil del usuario (JPG, PNG, WebP o SVG).
   */
  avatar?: (number | null) | Media;
  refreshTokenHash?: string | null;
  refreshTokenExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  nombre: {
    es: string;
    en: string;
  };
  descripcion?: {
    es?: string | null;
    en?: string | null;
  };
  slug: string;
  imagen?: (number | null) | Media;
  /**
   * Cuenta Instagram de esta categoría (aparece en la página de categoría y en el footer).
   */
  instagram_url?: string | null;
  /**
   * Optimización para buscadores y redes. Si dejas un campo vacío, se usan el nombre y la descripción del registro.
   */
  seo?: {
    meta_title?: {
      es?: string | null;
      en?: string | null;
    };
    meta_description?: {
      es?: string | null;
      en?: string | null;
    };
    keywords?: {
      es?: string | null;
      en?: string | null;
    };
    /**
     * Opcional. Si está vacío se usa la URL de esta página.
     */
    canonical_url?: string | null;
    og_title?: {
      es?: string | null;
      en?: string | null;
    };
    og_description?: {
      es?: string | null;
      en?: string | null;
    };
    og_image?: (number | null) | Media;
    twitter_title?: {
      es?: string | null;
      en?: string | null;
    };
    twitter_description?: {
      es?: string | null;
      en?: string | null;
    };
    twitter_image?: (number | null) | Media;
    robots?: ('index, follow' | 'noindex, follow' | 'noindex, nofollow' | 'index' | 'noindex') | null;
    /**
     * JSON-LD opcional. Si está vacío, la tienda genera automáticamente Product o CollectionPage.
     */
    structured_data?: string | null;
  };
  social?: {
    instagram_url?: string | null;
    facebook_url?: string | null;
    whatsapp_url?: string | null;
    tiktok_url?: string | null;
  };
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  nombre: {
    es: string;
    en: string;
  };
  descripcion: {
    es: string;
    en: string;
  };
  ingredientes?: {
    es?: string | null;
    en?: string | null;
  };
  slug: string;
  precio: number;
  calorias?: number | null;
  categoria: number | Category;
  /**
   * Hasta 5 imágenes o videos para el producto.
   */
  galeria?: (number | Media)[] | null;
  /**
   * Campo legado. Usa Galería.
   */
  imagen?: (number | null) | Media;
  atributos?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optimización para buscadores y redes. Si dejas un campo vacío, se usan el nombre y la descripción del registro.
   */
  seo?: {
    meta_title?: {
      es?: string | null;
      en?: string | null;
    };
    meta_description?: {
      es?: string | null;
      en?: string | null;
    };
    keywords?: {
      es?: string | null;
      en?: string | null;
    };
    /**
     * Opcional. Si está vacío se usa la URL de esta página.
     */
    canonical_url?: string | null;
    og_title?: {
      es?: string | null;
      en?: string | null;
    };
    og_description?: {
      es?: string | null;
      en?: string | null;
    };
    og_image?: (number | null) | Media;
    twitter_title?: {
      es?: string | null;
      en?: string | null;
    };
    twitter_description?: {
      es?: string | null;
      en?: string | null;
    };
    twitter_image?: (number | null) | Media;
    robots?: ('index, follow' | 'noindex, follow' | 'noindex, nofollow' | 'index' | 'noindex') | null;
    /**
     * JSON-LD opcional. Si está vacío, la tienda genera automáticamente Product o CollectionPage.
     */
    structured_data?: string | null;
  };
  social?: {
    instagram_url?: string | null;
    facebook_url?: string | null;
    whatsapp_url?: string | null;
    tiktok_url?: string | null;
  };
  featured?: boolean | null;
  sales_count?: number | null;
  view_count?: number | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  status: 'pending' | 'confirmed' | 'preparing' | 'ready' | 'in_transit' | 'delivered' | 'returned' | 'cancelled';
  /**
   * Usuarios con rol delivery, operador o super admin.
   */
  delivery?: (number | null) | User;
  user?: (number | null) | User;
  total: number;
  payment_method: 'cash' | 'transfer';
  payment_account?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  address:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contact_primary:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contact_secondary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  scheduled_date?: string | null;
  scheduled_time?: string | null;
  currency?: ('DOP' | 'USD') | null;
  exchange_rate_snapshot?: number | null;
  /**
   * Idioma del cliente al realizar el pedido (notificaciones).
   */
  customer_locale?: ('es' | 'en') | null;
  cancellation_reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  product: number | Product;
  quantity: number;
  price: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveries".
 */
export interface Delivery {
  id: number;
  user: number | User;
  status: 'available' | 'busy' | 'offline';
  current_order?: (number | null) | Order;
  delivery_history?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking-events".
 */
export interface TrackingEvent {
  id: number;
  event: 'view_product' | 'add_to_cart' | 'checkout_start' | 'purchase';
  user?: (number | null) | User;
  product?: (number | null) | Product;
  session_id?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reseñas de clientes. Aprueba las que quieras mostrar en el inicio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  user: number | User;
  author_name: string;
  rating: number;
  comment: string;
  /**
   * Solo las reseñas aprobadas aparecen en la página de inicio.
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Avisos automáticos de pedidos y respuestas a mensajes de soporte.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-notifications".
 */
export interface CustomerNotification {
  id: number;
  user: number | User;
  order?: (number | null) | Order;
  support_message?: (number | null) | SupportMessage;
  type: 'order_status' | 'message_reply' | 'system';
  title: string;
  body: string;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chats de soporte con clientes. Filtra por estado y responde desde la bandeja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-messages".
 */
export interface SupportMessage {
  id: number;
  user: number | User;
  order?: (number | null) | Order;
  source?: ('customer' | 'staff_order_cancel' | 'staff_initiated') | null;
  subject?: string | null;
  message?: string | null;
  status: 'received' | 'responded';
  /**
   * Al guardar una respuesta, el cliente recibirá una notificación.
   */
  admin_reply?: string | null;
  admin_reply_at?: string | null;
  /**
   * Mensajes adicionales del cliente y del equipo en este hilo.
   */
  thread?:
    | {
        role: 'customer' | 'staff';
        body: string;
        sent_at: string;
        deleted_for_customer?: boolean | null;
        deleted_for_staff?: boolean | null;
        id?: string | null;
      }[]
    | null;
  read_by_customer?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'deliveries';
        value: number | Delivery;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tracking-events';
        value: number | TrackingEvent;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'customer-notifications';
        value: number | CustomerNotification;
      } | null)
    | ({
        relationTo: 'support-messages';
        value: number | SupportMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  subRole?: T;
  nombre?: T;
  apellido?: T;
  nombreCompleto?: T;
  telefono?: T;
  delivery_address?:
    | T
    | {
        street?: T;
        city?: T;
        province?: T;
        reference?: T;
      };
  contact_secondary?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  avatar?: T;
  refreshTokenHash?: T;
  refreshTokenExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nombre?:
    | T
    | {
        es?: T;
        en?: T;
      };
  descripcion?:
    | T
    | {
        es?: T;
        en?: T;
      };
  slug?: T;
  imagen?: T;
  instagram_url?: T;
  seo?:
    | T
    | {
        meta_title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        meta_description?:
          | T
          | {
              es?: T;
              en?: T;
            };
        keywords?:
          | T
          | {
              es?: T;
              en?: T;
            };
        canonical_url?: T;
        og_title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        og_description?:
          | T
          | {
              es?: T;
              en?: T;
            };
        og_image?: T;
        twitter_title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        twitter_description?:
          | T
          | {
              es?: T;
              en?: T;
            };
        twitter_image?: T;
        robots?: T;
        structured_data?: T;
      };
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  nombre?:
    | T
    | {
        es?: T;
        en?: T;
      };
  descripcion?:
    | T
    | {
        es?: T;
        en?: T;
      };
  ingredientes?:
    | T
    | {
        es?: T;
        en?: T;
      };
  slug?: T;
  precio?: T;
  calorias?: T;
  categoria?: T;
  galeria?: T;
  imagen?: T;
  atributos?: T;
  seo?:
    | T
    | {
        meta_title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        meta_description?:
          | T
          | {
              es?: T;
              en?: T;
            };
        keywords?:
          | T
          | {
              es?: T;
              en?: T;
            };
        canonical_url?: T;
        og_title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        og_description?:
          | T
          | {
              es?: T;
              en?: T;
            };
        og_image?: T;
        twitter_title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        twitter_description?:
          | T
          | {
              es?: T;
              en?: T;
            };
        twitter_image?: T;
        robots?: T;
        structured_data?: T;
      };
  featured?: T;
  sales_count?: T;
  view_count?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  delivery?: T;
  user?: T;
  total?: T;
  payment_method?: T;
  payment_account?: T;
  address?: T;
  contact_primary?: T;
  contact_secondary?: T;
  scheduled_date?: T;
  scheduled_time?: T;
  currency?: T;
  exchange_rate_snapshot?: T;
  customer_locale?: T;
  cancellation_reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  quantity?: T;
  price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveries_select".
 */
export interface DeliveriesSelect<T extends boolean = true> {
  user?: T;
  status?: T;
  current_order?: T;
  delivery_history?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking-events_select".
 */
export interface TrackingEventsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  product?: T;
  session_id?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  user?: T;
  author_name?: T;
  rating?: T;
  comment?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-notifications_select".
 */
export interface CustomerNotificationsSelect<T extends boolean = true> {
  user?: T;
  order?: T;
  support_message?: T;
  type?: T;
  title?: T;
  body?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-messages_select".
 */
export interface SupportMessagesSelect<T extends boolean = true> {
  user?: T;
  order?: T;
  source?: T;
  subject?: T;
  message?: T;
  status?: T;
  admin_reply?: T;
  admin_reply_at?: T;
  thread?:
    | T
    | {
        role?: T;
        body?: T;
        sent_at?: T;
        deleted_for_customer?: T;
        deleted_for_staff?: T;
        id?: T;
      };
  read_by_customer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Tasa de cambio, métricas internas y datos del sistema. Los textos de la tienda están en «Mensajes de la tienda» (Globals → Contenido).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Tasa de cambio USD → DOP
   */
  exchange_rate_usd: number;
  brand_name?: string | null;
  /**
   * Gasto de marketing acumulado (para CAC)
   */
  marketing_spend?: number | null;
  site_visits?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos visibles en la tienda, organizados por pestañas: inicio, sobre nosotros, FAQ, legal, footer, menú, contacto, pagos e Instagram.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-content".
 */
export interface StoreContent {
  id: number;
  home?: {
    hero_title?: {
      es?: string | null;
      en?: string | null;
    };
    hero_subtitle?: {
      es?: string | null;
      en?: string | null;
    };
    shop_now?: {
      es?: string | null;
      en?: string | null;
    };
    reviews_title?: {
      es?: string | null;
      en?: string | null;
    };
    reviews_subtitle?: {
      es?: string | null;
      en?: string | null;
    };
    /**
     * URL de tu ficha de Google (ej. https://g.page/r/.../review). Si está vacío no se muestra el botón.
     */
    google_reviews_url?: string | null;
    google_reviews_label?: {
      es?: string | null;
      en?: string | null;
    };
  };
  about?: {
    title?: {
      es?: string | null;
      en?: string | null;
    };
    content?: {
      es?: string | null;
      en?: string | null;
    };
  };
  faq?: {
    title?: {
      es?: string | null;
      en?: string | null;
    };
    items?:
      | {
          question?: {
            es?: string | null;
            en?: string | null;
          };
          answer?: {
            es?: string | null;
            en?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  legal?: {
    terminos?: {
      title?: {
        es?: string | null;
        en?: string | null;
      };
      updated?: {
        es?: string | null;
        en?: string | null;
      };
      content?: {
        es?: string | null;
        en?: string | null;
      };
    };
    privacidad?: {
      title?: {
        es?: string | null;
        en?: string | null;
      };
      updated?: {
        es?: string | null;
        en?: string | null;
      };
      content?: {
        es?: string | null;
        en?: string | null;
      };
    };
    devoluciones?: {
      title?: {
        es?: string | null;
        en?: string | null;
      };
      updated?: {
        es?: string | null;
        en?: string | null;
      };
      content?: {
        es?: string | null;
        en?: string | null;
      };
    };
  };
  footer?: {
    tagline?: {
      es?: string | null;
      en?: string | null;
    };
    copyright_name?: string | null;
    rights?: {
      es?: string | null;
      en?: string | null;
    };
    developed_by?: {
      es?: string | null;
      en?: string | null;
    };
    developer_name?: string | null;
    developer_url?: string | null;
    rnc?: string | null;
  };
  nav?: {
    home?: {
      es?: string | null;
      en?: string | null;
    };
    shop?: {
      es?: string | null;
      en?: string | null;
    };
    categories?: {
      es?: string | null;
      en?: string | null;
    };
    account?: {
      es?: string | null;
      en?: string | null;
    };
    about?: {
      es?: string | null;
      en?: string | null;
    };
    faq?: {
      es?: string | null;
      en?: string | null;
    };
    terms?: {
      es?: string | null;
      en?: string | null;
    };
    privacy?: {
      es?: string | null;
      en?: string | null;
    };
    returns?: {
      es?: string | null;
      en?: string | null;
    };
    contact_heading?: {
      es?: string | null;
      en?: string | null;
    };
    quick_nav_heading?: {
      es?: string | null;
      en?: string | null;
    };
    legal_heading?: {
      es?: string | null;
      en?: string | null;
    };
    instagram_heading?: {
      es?: string | null;
      en?: string | null;
    };
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    /**
     * Ej: 18091234567 para tel:+18091234567
     */
    phone_digits?: string | null;
    /**
     * Ej: 18299876543 para wa.me/18299876543
     */
    whatsapp_digits?: string | null;
    whatsapp_display?: string | null;
    /**
     * Número al que el cliente enviará el comprobante de su pedido tras el checkout. Solo dígitos, ej: 18299876543.
     */
    order_confirmation_whatsapp?: string | null;
    address?: {
      es?: string | null;
      en?: string | null;
    };
    whatsapp_message?: {
      es?: string | null;
      en?: string | null;
    };
  };
  /**
   * Cuentas bancarias que verá el cliente al elegir transferencia en el checkout. Puedes añadir varias y el cliente escogerá a cuál pagar.
   */
  payment?: {
    /**
     * Cada cuenta se mostrará como una opción de pago. Añade al menos una con número de cuenta.
     */
    accounts?:
      | {
          holder_name?: string | null;
          bank_name?: string | null;
          /**
           * Obligatorio para mostrar la cuenta al cliente.
           */
          account_number?: string | null;
          account_type?: ('corriente' | 'ahorros') | null;
          currency?: ('DOP' | 'USD') | null;
          /**
           * RNC de la empresa o titular.
           */
          rnc?: string | null;
          document_id?: string | null;
          id?: string | null;
        }[]
      | null;
    transfer_instructions?: {
      es?: string | null;
      en?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  exchange_rate_usd?: T;
  brand_name?: T;
  marketing_spend?: T;
  site_visits?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-content_select".
 */
export interface StoreContentSelect<T extends boolean = true> {
  home?:
    | T
    | {
        hero_title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        hero_subtitle?:
          | T
          | {
              es?: T;
              en?: T;
            };
        shop_now?:
          | T
          | {
              es?: T;
              en?: T;
            };
        reviews_title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        reviews_subtitle?:
          | T
          | {
              es?: T;
              en?: T;
            };
        google_reviews_url?: T;
        google_reviews_label?:
          | T
          | {
              es?: T;
              en?: T;
            };
      };
  about?:
    | T
    | {
        title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        content?:
          | T
          | {
              es?: T;
              en?: T;
            };
      };
  faq?:
    | T
    | {
        title?:
          | T
          | {
              es?: T;
              en?: T;
            };
        items?:
          | T
          | {
              question?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
              answer?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  legal?:
    | T
    | {
        terminos?:
          | T
          | {
              title?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
              updated?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
              content?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
            };
        privacidad?:
          | T
          | {
              title?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
              updated?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
              content?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
            };
        devoluciones?:
          | T
          | {
              title?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
              updated?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
              content?:
                | T
                | {
                    es?: T;
                    en?: T;
                  };
            };
      };
  footer?:
    | T
    | {
        tagline?:
          | T
          | {
              es?: T;
              en?: T;
            };
        copyright_name?: T;
        rights?:
          | T
          | {
              es?: T;
              en?: T;
            };
        developed_by?:
          | T
          | {
              es?: T;
              en?: T;
            };
        developer_name?: T;
        developer_url?: T;
        rnc?: T;
      };
  nav?:
    | T
    | {
        home?:
          | T
          | {
              es?: T;
              en?: T;
            };
        shop?:
          | T
          | {
              es?: T;
              en?: T;
            };
        categories?:
          | T
          | {
              es?: T;
              en?: T;
            };
        account?:
          | T
          | {
              es?: T;
              en?: T;
            };
        about?:
          | T
          | {
              es?: T;
              en?: T;
            };
        faq?:
          | T
          | {
              es?: T;
              en?: T;
            };
        terms?:
          | T
          | {
              es?: T;
              en?: T;
            };
        privacy?:
          | T
          | {
              es?: T;
              en?: T;
            };
        returns?:
          | T
          | {
              es?: T;
              en?: T;
            };
        contact_heading?:
          | T
          | {
              es?: T;
              en?: T;
            };
        quick_nav_heading?:
          | T
          | {
              es?: T;
              en?: T;
            };
        legal_heading?:
          | T
          | {
              es?: T;
              en?: T;
            };
        instagram_heading?:
          | T
          | {
              es?: T;
              en?: T;
            };
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        phone_digits?: T;
        whatsapp_digits?: T;
        whatsapp_display?: T;
        order_confirmation_whatsapp?: T;
        address?:
          | T
          | {
              es?: T;
              en?: T;
            };
        whatsapp_message?:
          | T
          | {
              es?: T;
              en?: T;
            };
      };
  payment?:
    | T
    | {
        accounts?:
          | T
          | {
              holder_name?: T;
              bank_name?: T;
              account_number?: T;
              account_type?: T;
              currency?: T;
              rnc?: T;
              document_id?: T;
              id?: T;
            };
        transfer_instructions?:
          | T
          | {
              es?: T;
              en?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}